[package]
name = "rust_epitaph"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
 rand = "0.9.0"

[dependencies.uuid]
version = "1.16.0"
# Lets you generate random UUIDs
features = [
    "v4",
]